spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/editor}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true 
     
server:
    port: 8500
    
logging:
  level:
    com.upday: debug